blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from blog.apps import BlogConfig
from blog.views import (BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView,
                        BlogDeleteView, switching_publications)

app_name = BlogConfig.name

urlpatterns = [
                  path('create/', BlogCreateView.as_view(), name='create'),
                  path('', BlogListView.as_view(), name='list'),
                  path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
                  path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
                  path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
                  path('activity/<int:pk>', switching_publications, name='switching_publications'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls')),
    path('users/', include('users.urls')),
    path('blog/', include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path
from django.apps import apps
from mailings.apps import MailingsConfig
from mailings.views import MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView, \
    ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, MailingCreateView, \
    MailingDeleteView, MailingDetailView, MailingUpdateView, MailingListView, HomeListView, disable_the_mailing

app_name = MailingsConfig.name

MailingsConfig = apps.get_app_config('mailings')
MailingsConfig.ready()

urlpatterns = [
    path('', HomeListView.as_view(), name='home_list'),
    path('mailings/mailing_list/', MailingListView.as_view(), name='mailing_list'),
    path('mailings/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailings/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailings/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailings/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('messages/', MessageListView.as_view(), name='message_list'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('messages/create/', MessageCreateView.as_view(), name='message_create'),
    path('messages/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('messages/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('activity/<int:pk>', disable_the_mailing, name='disable_the_mailing'),
]

mailings/models.py
from django.db import models

from users.models import User


class Client(models.Model):
    email = models.EmailField(null=True, blank=True)
    full_name = models.CharField(max_length=100)
    comment = models.TextField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='clients')

    def __str__(self):
        return self.full_name


class Message(models.Model):
    topic = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self):
        return self.topic


class Mailing(models.Model):
    DAYLY = 'Раз в день'
    WEEKLY = 'Раз в неделю'
    MONTHLY = 'Раз в месяц'

    SENDING_PERIOD = [
        (DAYLY, 'Раз в день'),
        (WEEKLY, 'Раз в неделю'),
        (MONTHLY, 'Раз в месяц'),
    ]

    CREATED = 'Создана'
    STARTED = 'Запущена'
    FINISHED = 'Завершена'

    SELECT_STATUS = [
        (CREATED, 'Создана'),
        (STARTED, 'Запущена'),
        (FINISHED, 'Завершена'),
    ]

    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    frequency = models.CharField(max_length=20, choices=SENDING_PERIOD)
    status = models.CharField(default=CREATED, max_length=20, choices=SELECT_STATUS)
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    client = models.ManyToManyField(Client)
    is_disabled = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.start_date}-{self.end_date}, {self.frequency}, {self.status}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            ('disable_mailing', 'Может отключать рассылки'),
        ]


class MailingAttempt(models.Model):
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='ссылка на рассылку')
    attempt_date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)
    server_response = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытки рассылок'

    def __str__(self):
        return f'Попытка рассылки от {self.attempt_date} ({self.status})'

mailings/forms.py
from django import forms
from mailings.models import Client, Message, Mailing


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = ['email', 'full_name', 'comment']


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = ['topic', 'content']


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ['start_date', 'end_date', 'client', 'frequency', 'status', 'message']

mailings/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, ListView, DeleteView, CreateView, UpdateView
from django.apps import apps
from blog.models import BlogPost
from mailings.forms import ClientForm, MessageForm, MailingForm
from mailings.models import Client, Message, Mailing
import random

MailingsConfig = apps.get_app_config('mailings')
MailingsConfig.ready()


class HomeListView(ListView):
    model = Mailing
    template_name = 'mailing/home.html'
    context_object_name = 'mailings'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailings = Mailing.objects.all()
        active_mailings = mailings.filter(status='Запущена').count()
        unique_clients = Client.objects.filter(mailing__in=mailings).distinct('id').count()
        total_mailings = mailings.count()
        all_blogs = list(BlogPost.objects.all())
        random.shuffle(all_blogs)
        context['object_list'] = all_blogs[:3]
        context['active_mailings'] = active_mailings
        context['unique_clients'] = unique_clients
        context['total_mailings'] = total_mailings
        return context


class MailingListView(ListView):
    model = Mailing
    template_name = 'mailing/mailing_list.html'
    context_object_name = 'mailings'


def disable_the_mailing(request, pk):
    mailing_item = get_object_or_404(Mailing, pk=pk)
    if mailing_item.status == "Запущена":
        mailing_item.status = "Завершена"

    elif mailing_item.status == "Завершена":
        mailing_item.status = "Запущена"

    mailing_item.save()

    return redirect(reverse('mailings:mailing_list'))


class MailingDetailView(DetailView):
    model = Mailing
    template_name = 'mailing/mailing_detail.html'
    context_object_name = 'mailings'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['clients'] = self.object.client.all()
        return context


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_form.html'
    success_url = reverse_lazy('mailings:mailing_list')

    def form_valid(self, form):
        return super().form_valid(form)


class MailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_form.html'
    success_url = reverse_lazy('mailings:mailing_list')


class MailingDeleteView(DeleteView):
    model = Mailing
    template_name = 'mailing/mailing_confirm_delete.html'
    success_url = reverse_lazy('mailings:mailing_list')


class ClientListView(ListView):
    model = Client
    template_name = 'mailing/client_list.html'
    context_object_name = 'mailings:client_list'


class ClientDetailView(DetailView):
    model = Client
    template_name = 'mailing/client_detail.html'
    success_url = reverse_lazy('mailings:client_list')

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Просмотр клиента'
        return context_data


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
    template_name = 'mailing/client_form.html'
    success_url = reverse_lazy('mailings:client_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'mailing/client_form.html'
    success_url = reverse_lazy('mailings:client_list')


class ClientDeleteView(DeleteView):
    model = Client
    template_name = 'mailing/client_confirm_delete.html'
    success_url = reverse_lazy('mailings:client_list')


class MessageListView(ListView):
    model = Message
    template_name = 'mailing/message_list.html'
    context_object_name = 'mailings:messages_list'


class MessageDetailView(DetailView):
    model = Message
    template_name = 'mailing/message_detail.html'
    success_url = reverse_lazy('mailings:message_list')

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Просмотр сообщения'
        return context_data


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    template_name = 'mailing/message_form.html'
    success_url = reverse_lazy('mailings:message_list')

    def form_valid(self, form):
        return super().form_valid(form)


class MessageUpdateView(UpdateView):
    model = Message
    form_class = MessageForm
    template_name = 'mailing/message_form.html'
    success_url = reverse_lazy('mailings:message_list')


class MessageDeleteView(DeleteView):
    model = Message
    template_name = 'mailing/message_confirm_delete.html'
    success_url = reverse_lazy('mailings:message_list')

mailings/templates/mailing/client_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <h5 class="text-center mb-4">Вы уверены, что хотите удалить клиента - {{ object.full_name }}?</h5>
                        <div class="text-center">
                            <button type="submit" class="btn btn-danger mx-2">Удалить</button>
                            <a href="{% url 'mailings:client_list' %}" class="btn btn-warning mx-2">Отмена</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailings/templates/mailing/client_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-sm">
                <div class="card-header bg-secondary text-white">
                    <h4 class="card-title mb-0">Клиент №{{ object.pk }}</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                                <p><strong>Почта:</strong> {{ object.email }}</p>
                                <p><strong>ФИО:</strong> {{ object.full_name }}</p>
                                <p><strong>Содержание сообщения:</strong></p>
                                <p>{{ object.comment }}</p>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'mailings:client_list' %}" class="btn btn-secondary">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailings/templates/mailing/client_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="card">
                <h3 class="card-title text-center">
                    {% if object %}
                        Редактирование клиента
                    {% else %}
                        Создание клиента
                    {% endif %}
                </h3>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                        <a class="btn btn-outline-secondary" href="{% url 'mailings:client_list' %}">Назад</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailing/client_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-5">
    <a href="{% url 'mailings:client_create' %}" class="btn btn-outline-primary">Добавить клиента</a>
</div>

<div class="container my-6">
    <div class="row justify-content-center">
        {% for object in object_list|slice:100 %}
            <div class="col-md-4 mb-4 d-flex align-items-stretch">
                <div class="card shadow-sm">
                    <div class="card-header bg-secondary text-white">
                        <h4 class="card-title mb-0">Клиент №{{ object.pk }}</h4>
                    </div>
                    <div class="card-body d-flex flex-column">
                        <div class="row">
                            <div class="col-md-12">
                                <p><strong>Почта:</strong> {{ object.email }}</p>
                                <p><strong>ФИО:</strong> {{ object.full_name }}</p>
                                <p><strong>Содержание сообщения:</strong></p>
                                <p>{{ object.comment }}</p>
                            </div>
                        </div>
                        <div class="mt-auto">
                            <div class="d-flex justify-content-between align-items-center mt-3">
                                <div class="btn-group btn-group-sm">
                                    <a class="btn btn-primary mr-2" href="{% url 'mailings:client_detail' object.pk %}">Посмотреть</a>
                                    {% if not object or object.user == user or user.is_superuser %}
                                        <a class="btn btn-warning mr-2" href="{% url 'mailings:client_update' object.pk %}">Редактировать</a>
                                        <a class="btn btn-danger" href="{% url 'mailings:client_delete' object.pk %}">Удалить</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

mailings/templates/mailing/home.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Сервис Рассылок</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
</head>
<body>
    {% include 'mailing/includes/inc_main_menu.html' %}

    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="card shadow-sm">
                    <div class="card-header bg-primary text-white text-center">
                        <h3 class="mb-0">Сервис Рассылок</h3>
                    </div>
                    <div class="card-body">
                        <div class="mb-3">
                            <p>Количество рассылок всего: <strong>{{ total_mailings }}</strong></p>
                            <p>Количество активных рассылок: <strong>{{ active_mailings }}</strong></p>
                            <p>Количество уникальных клиентов для рассылок: <strong>{{ unique_clients }}</strong></p>
                        </div>

                        <h4 class="mb-4">Три статьи из блога:</h4>
                        <div class="row">
                            {% for blog in object_list %}
                            <div class="col-md-4 mb-4">
                                <div class="card h-100">
                                    <img src="{{ blog.image.url }}" class="card-img-top" alt="{{ blog.title }}">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ blog.title }}</h5>
                                        <p class="card-text">{{ blog.content }}</p>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer class="footer mt-auto py-3 bg-dark text-white">
        <div class="container">
            <p class="text-center mb-0">© 2024 Сервис Рассылок</p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

mailings/templates/mailing/mailing_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <h5 class="text-center mb-4">Вы уверены, что хотите удалить рассылку под номером - {{ object.pk }}?</h5>
                        <div class="text-center">
                            <button type="submit" class="btn btn-danger mx-2">Удалить</button>
                            <a href="{% url 'mailings:mailing_list' %}" class="btn btn-warning mx-2">Отмена</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailings/templates/mailing/mailing_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-sm">
                <div class="card-header bg-secondary text-white">
                    <h4 class="card-title mb-0">Рассылка №{{ object.pk }}</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>Начало отправки:</strong> {{ object.start_date }}</p>
                            <p><strong>Конец отправки:</strong> {{ object.end_date }}</p>
                            <p><strong>Период рассылки:</strong> {{ object.get_frequency_display }}</p>
                            <p><strong>Статус рассылки:</strong> {{ object.get_status_display }}</p>
                        </div>
                        <div class="col-md-6">
                            <p><strong>Тема сообщения:</strong> {{ object.message.topic }}</p>
                            <p><strong>Содержание сообщения:</strong></p>
                            <p>{{ object.message.content }}</p>
                        </div>
                    </div>

                    <h5 class="mt-4">Список клиентов:</h5>
                    <ul class="list-group">
                        {% for client in clients %}
                        <li class="list-group-item">{{ client.full_name }} ({{ client.email }})</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="card-footer">
                    <a href="{% url 'mailings:mailing_list' %}" class="btn btn-secondary">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailings/templates/mailing/mailing_form.html
{% extends "base.html" %}

{% block title %}Создание Рассылки{% endblock %}

{% block content %}
<div class="container py-5">
    <h1 class="mb-4">
        {% if object %}
            Редактирование рассылки
        {% else %}
            Создание рассылки
        {% endif %}
    </h1>
    <div class="card shadow rounded-lg">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
                <a href="{% url 'mailings:mailing_list' %}" class="btn btn-secondary">Назад</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailing/mailing_list.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Сервис Рассылок{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
    {% include 'mailing/includes/inc_main_menu.html' %}

    <div class="container my-5">
        {% block content %}
            <a href="{% url 'mailings:mailing_create' %}" class="btn btn-success mb-3">Создать рассылку</a>
        {% endblock %}
    </div>

    <div class="container">
        <div class="row justify-content-center">
            {% for object in object_list|slice:100 %}
                {% if not object or object.user == user or user.is_superuser or object_groups_user == object_groups %}
                    <div class="col-md-5 mb-4">
                        <div class="card h-100 shadow-sm">
                            <div class="card-header bg-secondary text-white">
                                <h4 class="my-0 fw-normal">Номер рассылки - {{ object.pk }}</h4>
                            </div>
                            <div class="card-body d-flex flex-column justify-content-between">
                                <div class="mb-3">
                                    <p class="mb-1">Начало отправки: {{ object.start_date }}</p>
                                    <p class="mb-1">Конец отправки: {{ object.end_date }}</p>
                                    <p class="mb-1">Период рассылки: {{ object.frequency }}</p>
                                    <p class="mb-1">Статус рассылки: {{ object.status }}</p>
                                    <p class="mb-1">Тема сообщения: {{ object.message }}</p>
                                </div>
                                <div class="d-flex justify-content-between align-items-end flex-column flex-md-row">
                                    <div class="btn-group btn-group-sm mb-2 mb-md-0">
                                        <a class="btn btn-primary mr-2" href="{% url 'mailings:mailing_detail' object.pk %}">Посмотреть</a>
                                        {% if not object or object.user == user or user.is_superuser %}
                                            <a class="btn btn-warning mr-2" href="{% url 'mailings:mailing_update' object.pk %}">Редактировать</a>
                                            <a class="btn btn-danger mr-2" href="{% url 'mailings:mailing_delete' object.pk %}">Удалить</a>
                                        {% endif %}
                                        {% if perms.mailings.disable_mailing %}
                                            {% if object.status == 'Запущена' %}
                                                <a class="btn btn-sm btn-warning mr-2" href="{% url 'mailings:disable_the_mailing' object.pk %}">Завершить</a>
                                            {% elif object.status == 'Завершена' %}
                                                <a class="btn btn-sm btn-success" href="{% url 'mailings:disable_the_mailing' object.pk %}">Запустить</a>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>

    <footer class="footer mt-auto py-3 bg-dark text-white">
        <div class="container">
            <p class="text-center">© 2024 Сервис Рассылок</p>
        </div>
    </footer>
</body>
</html>

mailings/templates/mailing/message_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <h5 class="text-center mb-4">Вы уверены, что хотите удалить сообщение под номером - {{ object.pk }}?</h5>
                        <div class="text-center">
                            <button type="submit" class="btn btn-danger mx-2">Удалить</button>
                            <a href="{% url 'mailings:message_list' %}" class="btn btn-warning mx-2">Отмена</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailings/templates/mailing/message_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-sm">
                <div class="card-header bg-secondary text-white">
                    <h4 class="card-title mb-0">Сообщение №{{ object.pk }}</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <p><strong>Тема сообщения:</strong> {{ object.topic }}</p>
                            <p><strong>Содержание сообщения:</strong></p>
                            <p>{{ object.content }}</p>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'mailings:message_list' %}" class="btn btn-secondary">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailings/templates/mailing/message_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="card">
                <h3 class="card-title text-center">
                    {% if object %}
                        Редактирование сообщения
                    {% else %}
                        Создание сообщения
                    {% endif %}
                </h3>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                        <a class="btn btn-outline-secondary" href="{% url 'mailings:message_list' %}">Назад</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailing/message_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container my-5">
    <a href="{% url 'mailings:message_create' %}" class="btn btn-outline-primary">Добавить сообщение</a>
</div>

<div class="container my-6">
    <div class="row justify-content-center">
        {% for object in object_list|slice:100 %}
            <div class="col-md-4 mb-4 d-flex align-items-stretch">
                <div class="card shadow-sm">
                    <div class="card-header bg-secondary text-white">
                        <h4 class="card-title mb-0">Сообщение №{{ object.pk }}</h4>
                    </div>
                    <div class="card-body d-flex flex-column">
                        <div class="row">
                            <div class="col-md-12">
                                <p><strong>Тема сообщения:</strong> {{ object.topic }}</p>
                                <p><strong>Содержание сообщения:</strong></p>
                                <p>{{ object.content }}</p>
                            </div>
                        </div>
                        <div class="mt-auto">
                            <div class="d-flex justify-content-between align-items-center mt-3">
                                <div class="btn-group btn-group-sm">
                                    <a class="btn btn-primary mr-2" href="{% url 'mailings:message_detail' object.pk %}">Посмотреть</a>
                                    {% if not object or object.user == user or user.is_superuser %}
                                        <a class="btn btn-warning mr-2" href="{% url 'mailings:message_update' object.pk %}">Редактировать</a>
                                        <a class="btn btn-danger" href="{% url 'mailings:message_delete' object.pk %}">Удалить</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}